In [1]:
# Q 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
# Ans. Earlier there is no any specific tool in python to perform the numerical functions , hence the NumPy was introduced.
# How it enhance the python capabilities for numerical functions:-
# >> as numpy built using the c which is fastest language after c++ hence it compute it faster.
# >> numpy use array which store homogeneous data only hence it compute faster.


In [3]:
# Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# Ans. Both we use to calculate the numerical data, but there were some differences;
# >> np.mean() compute the arithmetic mean of the input array ,while np.average() computes the weighted avg of the input array if weights are provided otherwise, it behaves same as the np.mean().
# >>np.mean() doesnot support weighting, it computes a simple mean by summing the elements and dividing by the total number of elements. 
#      While np.average() support weighting.these is useful when you need a mean that takes into account the importance or frequency of different elements.
# >> when we need simple arithmetic mean we use np.mean(), while when we need weighted average we use np.average(). 


In [5]:

# Q 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# Ans. It involves changing the order of elements in the array, which can be done along a different axes.


In [15]:
# 1D arrays-
import numpy as np
A = np.array([1,2,3,4,5,6])
Revr_a =A[: :-1]
print ("original arrays",A)
print("reversed " , Revr_a)


original arrays [1 2 3 4 5 6]
reversed  [6 5 4 3 2 1]


In [ ]:
# 2D array :-  
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
Rev_clm = A[: :-1, :]
Print("reversed along clm : \n",rev_clm)
Rev_row  = B[:, :  : -1]
print("reversed along row: \n",rev _row)

In [23]:
# Q.4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance.
# Ans. to determine the data type of elements in a numpy array, we can use the .dtype atrribute of the array.

#     importance of datatype.
# >> data type determine the amont of memory each element in an array occupies.

# >> the data type affects computation performance.

# >> data type affects the accuracy of numerical computation.

# >> it ensure the correct data type is also important for other libraries.

In [25]:
# Q.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
# Ans. nd arrays are a fundamental data sturcture  in the numpy library. they represent a grid of values, all of the same type,indexed by a tuple of non-negetive integers.

# key features:-

# >> it takes homogeneous data.
# >> nd arrays can have one or more dimensions,making them flexible for representing various data structure.
# >> it is memory efficient.
# >> is support indexing , slicing.

# diffence from standard list:

# >> nd array support vectorized operations. like A+B it will add all the corresponding elements.while in list A+B it will concatinate both the list.

# >> nd arrays stores homogeneous data type , while list store hetrogeneous data type.

# >> it has built-in methods for numerical operations, while in list we have to run a loop for that.

In [27]:
# Q.6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operation

# Ans. numpy array offers significant performance  beneits over pyhthon list like:

# >> numpy array are more memory efficient the a list.
# >> numpy arrays supports vectorized operation that means it perform calculation with running a loop ,while in list we need to run a loop.
# >> numpy built using c progarming language which make it faster to perform task then list,
# >> numpy support homogeneous data type while list support heterogenous datatype.
# >> numpy support advanced mathematical operation while in list to perform such task it need  a external modules and additional coding.

In [31]:
# Q.7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.
# ans. vstack():- stacks arrays vertically. it joins two or more arrays along a vertical axis.array should have same no. of columns.
#      hstack() :- stacks arrays horizontally. join arrays along a horizontal axix. it must have same no.of rows.

# example:-
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
result1 = np.vstack((a,b))
print("vstack :_")
print("result1")
result2 = np.hstack((a,b))
print("hstack :")
print(result2)

vstack :_
result1
hstack :
[1 2 3 4 5 6]


In [1]:
# Q.8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions.
# Ans. fliplr and flipud in numpy are the function used to reverse the order of elements in an arrayalong a specific axes.

#     diference:-
# >> np.fliplr means flip left to right, it flips the array horizontally,, while flipud means flip up-down,, it flip the array vertically/
# >> fliplr work only on 2D or high dimentional array, while flipud work on any dimention.
# >> fliplr reverce the order of the column , while flipud reverse the order of the row.

In [3]:
#   Q. 9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# ans:- np.array_split is used to split an array into multiple sub-arrays. it is flexible because it  can handle the array cannot be split into equal parts.

# >> in case of uneven split it will distribute the excess elements among the earlier sections.

# example ;

import numpy as np
a = np.array([1,2,3,4,5])
spl_a = np.array_split(a , 3)
print(spl_a)


[array([1, 2]), array([3, 4]), array([5])]


In [1]:
#  Q.10 .Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
# operations?
# Ans. vectorization :- it is the process of performing operation on entier arrays at once rather than looping through individual element.

#      broadcasting:- it is the mechanism that allows numpy to perform operations on arrays of different shapesby expanding one of it withput making its explicit copy.

#    contribution to efficient array;
# >> as it avoid loooping it reduce the memory overhead usage.
# >> broadcasting remove the manual replication of array which enhance the speed.
# >>by using these we make our code more shorter and readable.

## practical question

In [15]:
# Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
import random
arr =np.random.randint(1,100 ,size =(3,3))
print(arr)

[[25 29 71]
 [33 49 94]
 [51  8 43]]


In [19]:
array = np.array([[25,29,71],[33,49,94],[51,8,43]])
trans_array = array.T
print("original array")
print(arr)
print("tanspose array")
print(trans_array)

original array
[[25 29 71]
 [33 49 94]
 [51  8 43]]
tanspose array
[[25 33 51]
 [29 49  8]
 [71 94 43]]


In [31]:
# Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
print("reshape into 5,2 array")
arr.reshape(5,2)

reshape into 2,5 arry
reshape into 5,2 array


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
print("reshape into 2,5 arry")
arr.reshape(2,5)


reshape into 2,5 arry


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
# Q 3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array


In [47]:
# Q 4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np 
arr = np.arange(10,61,5)
print(arr)



[10 15 20 25 30 35 40 45 50 55 60]


In [55]:
# Q.5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np 
arr = np.array(['python','numpy','pandas'])
upper_c = np.char.upper(arr)
print(upper_c)
lower_c =np.char.lower(arr)
print(lower_c)
title_c = np.char.title(arr)
print(lower_c)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['python' 'numpy' 'pandas']


In [61]:
# Q.6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
words = np.array(['numpy','python','pw'])
space_w = np.array(['     '.join(word) for word in words])
print(space_w)

['n     u     m     p     y' 'p     y     t     h     o     n' 'p     w']


In [76]:
 #Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,22,33],[44,55,66]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[12 24 36]
 [48 60 72]]
[[-10 -20 -30]
 [-40 -50 -60]]
[[ 11  44  99]
 [176 275 396]]
[[0.09090909 0.09090909 0.09090909]
 [0.09090909 0.09090909 0.09090909]]


In [78]:
# Q.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np
arr = np.eye(5)
diagonal_elem= np.diag(arr)
print("identity mtrix  \n",arr)
print("diagonal elem  \n" ,diagonal_elem)

identity mtrix  
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
diagonal elem  
 [1. 1. 1. 1. 1.]


In [84]:
# Q.9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np
rand_int = np.random.randint(0,1001,size=100)
def is_prime(n):
    if n<=1:
        return False
    for i in range (2,int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
prime_ = [num for num in rand_int if is_prime(num)]
print("random integer \n",rand_int)
print("\n prime number  \n",prime_)

random integer 
 [893 525  85 470 328 227 651 641 674 816 123 633 286 719 434 900 303 936
 526 977 399 526 407 159 327 281 305 895 416  31 966 764 990 426 267 807
 363 388 485  98  50 178  85 935 445 608 303 208 626   5 113 179 476 267
  52 535 207 633 104 827 560 209 621 880 785 313 336 711 219 726 679 557
 824 307  96 204 888 765 754 997 830 564 125 360 776 973 767 822 129  35
 427 767 502 289 424 608 353 705  17 129]

 prime number  
 [227, 641, 719, 977, 281, 31, 5, 113, 179, 827, 313, 557, 307, 997, 353, 17]


In [86]:
 # Q.10Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np
daily_temp = np.random.randint(0 ,36 , size =30)
weekly_avg = daily_temp.reshape(4,).mean(axis=1)
print("daily temp  \n",daily_temp)
print("weekly temp  \n", weekly_avg)

ValueError: cannot reshape array of size 30 into shape (4,7)